export const FETCH_WEATHERS_REQUESTED = "FETCH_WEATHERS_REQUESTED";
export const FETCH_WEATHERS_SUCCESSFULL = "FETCH_WEATHERS_SUCCESSFULL";
export const FETCH_WEATHERS_FAILED = "FETCH_WEATHERS_FAILED";
